'use strict';
const $=id=>document.getElementById(id);
let current=null, polling=false, timer=null, started=0;
async function api(path,options={}){const response=await fetch(path,options);const body=await response.json();if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body;}
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function busy(value){$('run').disabled=value;$('mode').disabled=value;$('history').disabled=value;$('progress').hidden=!value;clearInterval(timer);if(value){started=Date.now();const tick=()=>{$('progressText').textContent=`Running the pipeline… ${Math.floor((Date.now()-started)/1000)}s. The first run also loads the retrieval models.`;};tick();timer=setInterval(tick,1000);}}
function element(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
function pill(verdict){return element('span',verdict,'pill '+verdict.toLowerCase());}
async function history(){const runs=await api('/api/history');$('history').replaceChildren(new Option('Choose a saved run…',''));for(const r of runs)$('history').add(new Option(`${r.mode} · ${r.query} · ${new Date(r.timestamp).toLocaleTimeString()}`,r.id));return runs;}
function render(data,saved=false){current=data;const r=data.result;$('empty').hidden=true;$('result').hidden=false;$('tracePanel').hidden=false;$('runLabel').textContent=saved?'SAVED ACTUAL PIPELINE OUTPUT':'ACTUAL PIPELINE OUTPUT';$('question').textContent=r.query;$('verdict').replaceWith(Object.assign(pill(r.evidence_gate.status),{id:'verdict'}));$('answer').textContent=r.final_answer;$('trace').textContent=data.terminal;
 const expanded=r.slm_verification.filter(v=>v.parent_expansion).length;$('stats').replaceChildren();for(const [n,label] of [[r.retrieved_candidates.length,'candidates'],[r.final_evidence.length,'final passages'],[expanded,'parent expansions'],[r.timings.total_stage_seconds.toFixed(1)+'s','pipeline time']]){const item=element('span');item.append(element('strong',String(n)),document.createTextNode(label));$('stats').append(item);}
 const warnings=[...r.evidence_gate.warnings];if(r.generation.error)warnings.push('Final generation error: '+r.generation.error);if(r.cross_evidence_verification.error)warnings.push(r.cross_evidence_verification.error);$('warnings').textContent=warnings.join(' ');$('warnings').hidden=!warnings.length;
 $('provenance').textContent=`Mode ${r.mode} · ${new Date(r.timestamp).toLocaleString()} · Generator: ${r.generation.provider} · Run ${r.run_id}`;
 $('evidenceList').replaceChildren();const rows=r.mode==='C'?r.slm_verification:r.selected_evidence;for(const row of rows){const v=row.verification;const item=element('article',undefined,'evidence-item'),heading=element('div',undefined,'evidence-heading');heading.append(element('strong',row.source),pill(v?v.verdict:'UNVERIFIED'));item.append(heading);item.append(element('p',`${row.chunk_id} · page ${row.page} · similarity ${row.similarity_score.toFixed(4)}${row.reranker_score===undefined?'':` · reranker ${row.reranker_score.toFixed(4)}`}`));if(v){item.append(element('p',`Confidence ${v.confidence.toFixed(2)} · Parent expansion: ${row.parent_expansion?'yes':'no'} · ${v.reason}`));if(v.error)item.append(element('p','Blocked: '+v.error));}const details=element('details');details.append(element('summary','Inspect evidence and verification JSON'),element('pre',JSON.stringify(row,null,2)));item.append(details);$('evidenceList').append(item);}
 localStorage.setItem('slmRagLastRun',r.run_id);$('history').value=r.run_id;if(!saved)$('result').scrollIntoView({behavior:'smooth',block:'start'});
}
async function poll(id){if(polling)return;polling=true;busy(true);localStorage.setItem('slmRagJob',id);let failures=0;try{while(true){let job;try{job=await api('/api/jobs/'+encodeURIComponent(id));failures=0;}catch(e){if(++failures>=3)throw e;await new Promise(r=>setTimeout(r,1500));continue;}if(job.status==='complete'){await history();render(job);localStorage.removeItem('slmRagJob');break;}if(job.status==='error'){localStorage.removeItem('slmRagJob');throw new Error(job.error);}await new Promise(r=>setTimeout(r,1200));}}catch(e){error(e.message);}finally{polling=false;busy(false);}}
$('queryForm').addEventListener('submit',async e=>{e.preventDefault();error('');busy(true);$('result').hidden=true;$('tracePanel').hidden=true;$('empty').hidden=false;try{const job=await api('/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:$('query').value,mode:$('mode').value})});await poll(job.id);}catch(e){error(e.message);busy(false);}});
document.querySelectorAll('[data-example]').forEach(button=>button.addEventListener('click',()=>{$('query').value=button.dataset.example;$('query').focus();}));
$('mode').addEventListener('change',()=>{$('modeNote').textContent=$('mode').value==='C'?'Evidence is checked by the local SLM before final generation.':'Experimental baseline: this mode bypasses SLM verification. The architecture above describes mode C.';});
$('history').addEventListener('change',async()=>{if(!$('history').value)return;error('');try{render(await api('/api/saved/'+encodeURIComponent($('history').value)),true);}catch(e){error(e.message);}});
function download(text,extension,type){if(!current)return;const url=URL.createObjectURL(new Blob([text],{type}));const a=element('a');a.href=url;a.download=`slm-rag-${current.result.run_id}.${extension}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('downloadTrace').addEventListener('click',()=>download(current?.terminal||'','txt','text/plain;charset=utf-8'));
$('downloadJson').addEventListener('click',()=>download(JSON.stringify(current?.result,null,2),'json','application/json'));
async function init(){try{const status=await api('/api/status');$('health').textContent=status.model_ready?'● Local model ready':'○ Local model unavailable';$('model').textContent=`Verifier: ${status.model}. Retrieval ${status.retrieval_top_k} → reranked ${status.rerank_top_k}. All runs use the existing project.`;const past=await history();if(status.active_job){await poll(status.active_job);}else{localStorage.removeItem('slmRagJob');const previous=localStorage.getItem('slmRagLastRun')||past[0]?.id;if(previous){try{render(await api('/api/saved/'+encodeURIComponent(previous)),true);}catch{localStorage.removeItem('slmRagLastRun');}}}if(!status.model_ready)error('Run app.py again to start the configured local model automatically.');}catch(e){error(e.message);}}
init();
